name: DeepL Translation (Verbose, Stable)

on:
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          pip install requests-html langdetect beautifulsoup4 lxml[html-clean]

      - name: Run Translation Script
        run: |
          echo "Running debugVersion.py..."
          python debugVersion.py || (echo "debugVersion.py failed!" && exit 1)
