name: DeepL Translation

on:
  push:
    branches:
      - main  # Runs on push to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  translate:
    runs-on: ubuntu-latest  # Uses latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Cache pip packages
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}  # Unique key based on dependencies
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          pip install selenium mitmproxy requests
          sudo apt-get update
          sudo apt-get install -y xvfb chromium-chromedriver
          echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=$(which chromedriver)" >> $GITHUB_ENV

      - name: Run Translation Script
        env:
          DISPLAY: ":99"  # Needed for headless Chrome
        run: |
          Xvfb :99 -screen 0 1024x768x24 &  # Start virtual display
          python translate.py
